export const REGISTER_SUCCESS = 'REGISTER_USER'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const REGISTER_LOADING= 'REGISTER_LOADING'

export const LOGIN_SUCCESS = 'LOGIN_USER'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_LOADING= 'LOGIN_LOADING'

export const LOGOUT_SUCCESS = 'LOGOUT_USER'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'
export const LOGOUT_LOADING= 'LOGOUT_LOADING'

export const SET_USER = 'SET_USER'

export const GET_CARS = 'GET_CARS'
export const CARS_ERROR = 'CARS_ERROR'
export const CARS_LOADING= 'CARS_LOADING'

export const GET_USER_CARS = 'GET_USER_CARS'
export const CARS_USER_ERROR = 'CARS_USER_ERROR'
export const CARS_USER_LOADING = 'CARS_USER_LOADING'

export const GET_CARS_BRAND = 'GET_CATS_BRAND'
export const GET_CARS_MODEL = 'GET_CARS_MODEL'


export const DELETE_CAR = 'DELETE_CAR'
export const DELETE_CAR_ERROR = 'DELETE_CAR_ERROR'
