export const REGISTER_SUCCESS = 'REGISTER_USER'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const REGISTER_LOADING= 'REGISTER_LOADING'

export const LOGIN_SUCCESS = 'LOGIN_USER'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_LOADING= 'LOGIN_LOADING'